begin;

insert into public.teams
(name, abbr, coach_name, ac_name, conference, division, logo_url, primary_color, secondary_color, wins, losses, ties, points_for, points_against, ppg_for, ppg_against, streak, notes)
values
('Kansas City Chiefs', 'KC', '@always_chiefs', '@DelanesDomain5', 'AFC', 'AFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png', '#E31837', '#FFB81C', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Denver Broncos', 'DEN', '@PickedByPS2', '@SurtainGlazer', 'AFC', 'AFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png', '#FB4F14', '#002244', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Las Vegas Raiders', 'LV', '@SatansWrathful', '@RAIDERNTFL', 'AFC', 'AFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png', '#000000', '#A5ACAF', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Los Angeles Chargers', 'LAC', '@OmarionHamp2', '@PettyPDinero', 'AFC', 'AFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png', '#0080C6', '#FFC20E', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Cincinnati Bengals', 'CIN', '@Dude_Man_11', '@RDukes08', 'AFC', 'AFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png', '#FB4F14', '#000000', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Baltimore Ravens', 'BAL', '@H0LLYW00DCARLOS', '@HoodieYo8', 'AFC', 'AFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png', '#241773', '#000000', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Pittsburgh Steelers', 'PIT', '@Feed_DK', '', 'AFC', 'AFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png', '#101820', '#FFB612', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Cleveland Browns', 'CLE', '@martinsport2495', '', 'AFC', 'AFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png', '#311D00', '#FF3C00', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Tennessee Titans', 'TEN', '@InformedWatcher', '', 'AFC', 'AFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png', '#0C2340', '#4B92DB', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Houston Texans', 'HOU', '@CamIsKing11', '', 'AFC', 'AFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png', '#03202F', '#A71930', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Jacksonville Jaguars', 'JAX', '@liamcoenszn', '', 'AFC', 'AFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png', '#006778', '#9F792C', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Indianapolis Colts', 'IND', '@happystlfan4', '', 'AFC', 'AFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png', '#002C5F', '#A2AAAD', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Buffalo Bills', 'BUF', '@iancmcclintock', '@Valen59DaGoat', 'AFC', 'AFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png', '#00338D', '#C60C30', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Miami Dolphins', 'MIA', '@WydPoison', '@QuixProductions', 'AFC', 'AFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png', '#008E97', '#FC4C02', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('New York Jets', 'NYJ', '@Scotclone', '', 'AFC', 'AFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png', '#125740', '#000000', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('New England Patriots', 'NE', '@M_JWYouTube', '', 'AFC', 'AFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png', '#002244', '#C60C30', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Chicago Bears', 'CHI', '@burdenszn', '', 'NFC', 'NFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png', '#0B162A', '#C83803', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Detroit Lions', 'DET', '@MossedBySunGod', '', 'NFC', 'NFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png', '#0076B6', '#B0B7BC', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Green Bay Packers', 'GB', '@bug49_', '@NotOnGodOnRodge', 'NFC', 'NFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png', '#203731', '#FFB612', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Minnesota Vikings', 'MIN', '@GarganoSzn1', '', 'NFC', 'NFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png', '#4F2683', '#FFC62F', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Dallas Cowboys', 'DAL', '@ClaytonSkiles', '*NotLikeCeedee', 'NFC', 'NFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png', '#041E42', '#869397', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Philadelphia Eagles', 'PHI', '@BraedonMinarik', '@Philliesszn2026', 'NFC', 'NFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png', '#004C54', '#A5ACAF', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Washington Commanders', 'WAS', '@Xommanders', '@NateBG_22', 'NFC', 'NFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/was.png', '#5A1414', '#FFB612', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('New York Giants', 'NYG', '@wydpoint', '@Laf4MVP_
', 'NFC', 'NFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png', '#0B2265', '#A71930', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('New Orleans Saints', 'NO', '@ThomasBart17127 ', '@ihykronos', 'NFC', 'NFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png', '#D3BC8D', '#101820', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Carolina Panthers', 'CAR', '@gabriel_ki4939
', '', 'NFC', 'NFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png', '#0085CA', '#101820', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Atlanta Falcons', 'ATL', '@grae_visocan', '', 'NFC', 'NFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png', '#A71930', '#000000', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Tampa Bay Buccaneers', 'TB', '@bucsnationx210', '', 'NFC', 'NFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png', '#D50A0A', '#34302B', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Los Angeles Rams', 'LAR', '@Bucsfan6to13', '@ChickenNinja42', 'NFC', 'NFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png', '#003594', '#FFA300', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('San Francisco 49ers', 'SF', '@Ty_C13', '', 'NFC', 'NFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png', '#AA0000', '#B3995D', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Seattle Seahawks', 'SEA', '@wardangsports88', '@gregheffley2011', 'NFC', 'NFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png', '#002244', '#69BE28', 0, 0, 0, 0, 0, 'null', 'null', '', ''),
('Arizona Cardinals', 'ARI', '@watts__53
', '', 'NFC', 'NFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png', '#97233F', '#000000', 0, 0, 0, 0, 0, 'null', 'null', '', '')
on conflict (name) do update set
  abbr = excluded.abbr,
  coach_name = excluded.coach_name,
  ac_name = excluded.ac_name,
  conference = excluded.conference,
  division = excluded.division,
  logo_url = excluded.logo_url,
  primary_color = excluded.primary_color,
  secondary_color = excluded.secondary_color,
  wins = excluded.wins,
  losses = excluded.losses,
  ties = excluded.ties,
  points_for = excluded.points_for,
  points_against = excluded.points_against,
  ppg_for = excluded.ppg_for,
  ppg_against = excluded.ppg_against,
  streak = excluded.streak,
  notes = excluded.notes;

insert into public.schedule_games
(id, week, week_number, game_date, kickoff_time, home_team_name, away_team_name, home_score, away_score, status, is_live, spotlight, source_sheet, note)
values
('w1-seahawks-49ers', 'W1', 1, null, null, 'San Francisco 49ers', 'Seattle Seahawks', null, null, 'scheduled', false, false, 'NFC West', ''),
('w1-dolphins-bills', 'W1', 1, null, null, 'Buffalo Bills', 'Miami Dolphins', null, null, 'scheduled', false, false, 'AFC East', ''),
('w1-chiefs-broncos', 'W1', 1, null, null, 'Denver Broncos', 'Kansas City Chiefs', null, null, 'scheduled', false, false, 'AFC West', ''),
('w1-steelers-browns', 'W1', 1, null, null, 'Cleveland Browns', 'Pittsburgh Steelers', null, null, 'scheduled', false, false, 'AFC North', ''),
('w1-falcons-buccaneers', 'W1', 1, null, null, 'Tampa Bay Buccaneers', 'Atlanta Falcons', null, null, 'scheduled', false, false, 'NFC South', ''),
('w1-giants-cowboys', 'W1', 1, null, null, 'Dallas Cowboys', 'New York Giants', null, null, 'scheduled', false, false, 'NFC East', ''),
('w1-commanders-eagles', 'W1', 1, null, null, 'Philadelphia Eagles', 'Washington Commanders', null, null, 'scheduled', false, false, 'NFC East', ''),
('w1-titans-jaguars', 'W1', 1, null, null, 'Jacksonville Jaguars', 'Tennessee Titans', null, null, 'scheduled', false, false, 'AFC South', ''),
('w1-lions-packers', 'W1', 1, null, null, 'Green Bay Packers', 'Detroit Lions', null, null, 'scheduled', false, false, 'NFC North', ''),
('w1-jets-patriots', 'W1', 1, null, null, 'New England Patriots', 'New York Jets', null, null, 'scheduled', false, false, 'AFC East', ''),
('w1-chargers-raiders', 'W1', 1, null, null, 'Las Vegas Raiders', 'Los Angeles Chargers', null, null, 'scheduled', false, false, 'AFC West', ''),
('w1-cardinals-rams', 'W1', 1, null, null, 'Los Angeles Rams', 'Arizona Cardinals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w1-bengals-ravens', 'W1', 1, null, null, 'Baltimore Ravens', 'Cincinnati Bengals', null, null, 'scheduled', false, false, 'AFC North', ''),
('w1-panthers-41-38-ot-saints', 'W1', 1, null, null, 'New Orleans Saints', 'Panthers (41-38) OT', null, null, 'scheduled', false, false, 'NFC South', ''),
('w1-panthers-saints-38-41-ot', 'W1', 1, null, null, 'Saints (38-41) OT', 'Carolina Panthers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w1-colts-texans', 'W1', 1, null, null, 'Houston Texans', 'Indianapolis Colts', null, null, 'scheduled', false, false, 'AFC South', ''),
('w1-bears-vikings', 'W1', 1, null, null, 'Minnesota Vikings', 'Chicago Bears', null, null, 'scheduled', false, false, 'NFC North', ''),
('w2-rams-49ers', 'W2', 2, null, null, 'San Francisco 49ers', 'Los Angeles Rams', null, null, 'scheduled', false, false, 'NFC West', ''),
('w2-steelers-bengals', 'W2', 2, null, null, 'Cincinnati Bengals', 'Pittsburgh Steelers', null, null, 'scheduled', false, false, 'AFC North', ''),
('w2-patriots-bills', 'W2', 2, null, null, 'Buffalo Bills', 'New England Patriots', null, null, 'scheduled', false, false, 'AFC East', ''),
('w2-raiders-broncos', 'W2', 2, null, null, 'Denver Broncos', 'Las Vegas Raiders', null, null, 'scheduled', false, false, 'AFC West', ''),
('w2-saints-buccaneers', 'W2', 2, null, null, 'Tampa Bay Buccaneers', 'New Orleans Saints', null, null, 'scheduled', false, false, 'NFC South', ''),
('w2-chargers-chiefs', 'W2', 2, null, null, 'Kansas City Chiefs', 'Los Angeles Chargers', null, null, 'scheduled', false, false, 'AFC West', ''),
('w2-titans-colts', 'W2', 2, null, null, 'Indianapolis Colts', 'Tennessee Titans', null, null, 'scheduled', false, false, 'AFC South', ''),
('w2-eagles-cowboys', 'W2', 2, null, null, 'Dallas Cowboys', 'Philadelphia Eagles', null, null, 'scheduled', false, false, 'NFC East', ''),
('w2-jets-dolphins', 'W2', 2, null, null, 'Miami Dolphins', 'New York Jets', null, null, 'scheduled', false, false, 'AFC East', ''),
('w2-panthers-falcons', 'W2', 2, null, null, 'Atlanta Falcons', 'Carolina Panthers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w2-commanders-giants', 'W2', 2, null, null, 'New York Giants', 'Washington Commanders', null, null, 'scheduled', false, false, 'NFC East', ''),
('w2-bears-lions', 'W2', 2, null, null, 'Detroit Lions', 'Chicago Bears', null, null, 'scheduled', false, false, 'NFC North', ''),
('w2-vikings-packers', 'W2', 2, null, null, 'Green Bay Packers', 'Minnesota Vikings', null, null, 'scheduled', false, false, 'NFC North', ''),
('w2-browns-ravens', 'W2', 2, null, null, 'Baltimore Ravens', 'Cleveland Browns', null, null, 'scheduled', false, false, 'AFC North', ''),
('w2-cardinals-seahawks', 'W2', 2, null, null, 'Seattle Seahawks', 'Arizona Cardinals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w2-jaguars-texans', 'W2', 2, null, null, 'Houston Texans', 'Jacksonville Jaguars', null, null, 'scheduled', false, false, 'AFC South', ''),
('w3-cardinals-49ers', 'W3', 3, null, null, 'San Francisco 49ers', 'Arizona Cardinals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w3-browns-bengals', 'W3', 3, null, null, 'Cincinnati Bengals', 'Cleveland Browns', null, null, 'scheduled', false, false, 'AFC North', ''),
('w3-jets-bills', 'W3', 3, null, null, 'Buffalo Bills', 'New York Jets', null, null, 'scheduled', false, false, 'AFC East', ''),
('w3-chargers-broncos', 'W3', 3, null, null, 'Denver Broncos', 'Los Angeles Chargers', null, null, 'scheduled', false, false, 'AFC West', ''),
('w3-panthers-buccaneers', 'W3', 3, null, null, 'Tampa Bay Buccaneers', 'Carolina Panthers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w3-raiders-chiefs', 'W3', 3, null, null, 'Kansas City Chiefs', 'Las Vegas Raiders', null, null, 'scheduled', false, false, 'AFC West', ''),
('w3-jaguars-colts', 'W3', 3, null, null, 'Indianapolis Colts', 'Jacksonville Jaguars', null, null, 'scheduled', false, false, 'AFC South', ''),
('w3-commanders-cowboys', 'W3', 3, null, null, 'Dallas Cowboys', 'Washington Commanders', null, null, 'scheduled', false, false, 'NFC East', ''),
('w3-patriots-dolphins', 'W3', 3, null, null, 'Miami Dolphins', 'New England Patriots', null, null, 'scheduled', false, false, 'AFC East', ''),
('w3-saints-falcons', 'W3', 3, null, null, 'Atlanta Falcons', 'New Orleans Saints', null, null, 'scheduled', false, false, 'NFC South', ''),
('w3-eagles-giants', 'W3', 3, null, null, 'New York Giants', 'Philadelphia Eagles', null, null, 'scheduled', false, false, 'NFC East', ''),
('w3-vikings-lions', 'W3', 3, null, null, 'Detroit Lions', 'Minnesota Vikings', null, null, 'scheduled', false, false, 'NFC North', ''),
('w3-bears-packers', 'W3', 3, null, null, 'Green Bay Packers', 'Chicago Bears', null, null, 'scheduled', false, false, 'NFC North', ''),
('w3-steelers-ravens', 'W3', 3, null, null, 'Baltimore Ravens', 'Pittsburgh Steelers', null, null, 'scheduled', false, false, 'AFC North', ''),
('w3-rams-seahawks', 'W3', 3, null, null, 'Seattle Seahawks', 'Los Angeles Rams', null, null, 'scheduled', false, false, 'NFC West', ''),
('w3-titans-texans', 'W3', 3, null, null, 'Houston Texans', 'Tennessee Titans', null, null, 'scheduled', false, false, 'AFC South', ''),
('w4-chiefs-buccaneers', 'W4', 4, null, null, 'Tampa Bay Buccaneers', 'Kansas City Chiefs', null, null, 'scheduled', false, false, 'NFC South', ''),
('w4-commanders-cardinals', 'W4', 4, null, null, 'Arizona Cardinals', 'Washington Commanders', null, null, 'scheduled', false, false, 'NFC West', ''),
('w4-panthers-cowboys', 'W4', 4, null, null, 'Dallas Cowboys', 'Carolina Panthers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w4-chargers-eagles', 'W4', 4, null, null, 'Philadelphia Eagles', 'Los Angeles Chargers', null, null, 'scheduled', false, false, 'NFC East', ''),
('w4-seahawks-falcons', 'W4', 4, null, null, 'Atlanta Falcons', 'Seattle Seahawks', null, null, 'scheduled', false, false, 'NFC West', ''),
('w4-lions-giants', 'W4', 4, null, null, 'New York Giants', 'Detroit Lions', null, null, 'scheduled', false, false, 'NFC North', ''),
('w4-bears-jaguars', 'W4', 4, null, null, 'Jacksonville Jaguars', 'Chicago Bears', null, null, 'scheduled', false, false, 'NFC North', ''),
('w4-browns-packers', 'W4', 4, null, null, 'Green Bay Packers', 'Cleveland Browns', null, null, 'scheduled', false, false, 'NFC North', ''),
('w4-titans-raiders', 'W4', 4, null, null, 'Las Vegas Raiders', 'Tennessee Titans', null, null, 'scheduled', false, false, 'AFC West', ''),
('w4-colts-rams', 'W4', 4, null, null, 'Los Angeles Rams', 'Indianapolis Colts', null, null, 'scheduled', false, false, 'NFC West', ''),
('w4-broncos-ravens', 'W4', 4, null, null, 'Baltimore Ravens', 'Denver Broncos', null, null, 'scheduled', false, false, 'AFC West', ''),
('w4-steelers-saints', 'W4', 4, null, null, 'New Orleans Saints', 'Pittsburgh Steelers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w4-bengals-texans', 'W4', 4, null, null, 'Houston Texans', 'Cincinnati Bengals', null, null, 'scheduled', false, false, 'AFC South', ''),
('w4-49ers-vikings', 'W4', 4, null, null, 'Minnesota Vikings', 'San Francisco 49ers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w5-jets-bears', 'W5', 5, null, null, 'Chicago Bears', 'New York Jets', null, null, 'scheduled', false, false, 'NFC North', ''),
('w5-colts-broncos', 'W5', 5, null, null, 'Denver Broncos', 'Indianapolis Colts', null, null, 'scheduled', false, false, 'AFC West', ''),
('w5-patriots-buccaneers', 'W5', 5, null, null, 'Tampa Bay Buccaneers', 'New England Patriots', null, null, 'scheduled', false, false, 'NFC South', ''),
('w5-eagles-cardinals', 'W5', 5, null, null, 'Arizona Cardinals', 'Philadelphia Eagles', null, null, 'scheduled', false, false, 'NFC West', ''),
('w5-raiders-cowboys', 'W5', 5, null, null, 'Dallas Cowboys', 'Las Vegas Raiders', null, null, 'scheduled', false, false, 'NFC East', ''),
('w5-packers-dolphins', 'W5', 5, null, null, 'Miami Dolphins', 'Green Bay Packers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w5-jaguars-giants', 'W5', 5, null, null, 'New York Giants', 'Jacksonville Jaguars', null, null, 'scheduled', false, false, 'NFC East', ''),
('w5-chargers-lions', 'W5', 5, null, null, 'Detroit Lions', 'Los Angeles Chargers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w5-chiefs-panthers', 'W5', 5, null, null, 'Carolina Panthers', 'Kansas City Chiefs', null, null, 'scheduled', false, false, 'NFC South', ''),
('w5-vikings-rams', 'W5', 5, null, null, 'Los Angeles Rams', 'Minnesota Vikings', null, null, 'scheduled', false, false, 'NFC West', ''),
('w5-commanders-saints', 'W5', 5, null, null, 'New Orleans Saints', 'Washington Commanders', null, null, 'scheduled', false, false, 'NFC South', ''),
('w5-bills-seahawks', 'W5', 5, null, null, 'Seattle Seahawks', 'Buffalo Bills', null, null, 'scheduled', false, false, 'NFC West', ''),
('w5-49ers-texans', 'W5', 5, null, null, 'Houston Texans', 'San Francisco 49ers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w5-falcons-titans', 'W5', 5, null, null, 'Tennessee Titans', 'Atlanta Falcons', null, null, 'scheduled', false, false, 'NFC South', ''),
('w6-eagles-49ers', 'W6', 6, null, null, 'San Francisco 49ers', 'Philadelphia Eagles', null, null, 'scheduled', false, false, 'NFC West', ''),
('w6-broncos-bears', 'W6', 6, null, null, 'Chicago Bears', 'Denver Broncos', null, null, 'scheduled', false, false, 'NFC North', ''),
('w6-falcons-bengals', 'W6', 6, null, null, 'Cincinnati Bengals', 'Atlanta Falcons', null, null, 'scheduled', false, false, 'NFC South', ''),
('w6-buccaneers-bills', 'W6', 6, null, null, 'Buffalo Bills', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w6-giants-browns', 'W6', 6, null, null, 'Cleveland Browns', 'New York Giants', null, null, 'scheduled', false, false, 'NFC East', ''),
('w6-ravens-chargers', 'W6', 6, null, null, 'Los Angeles Chargers', 'Baltimore Ravens', null, null, 'scheduled', false, false, 'AFC West', ''),
('w6-rams-chiefs', 'W6', 6, null, null, 'Kansas City Chiefs', 'Los Angeles Rams', null, null, 'scheduled', false, false, 'NFC West', ''),
('w6-dolphins-cowboys', 'W6', 6, null, null, 'Dallas Cowboys', 'Miami Dolphins', null, null, 'scheduled', false, false, 'NFC East', ''),
('w6-packers-jets', 'W6', 6, null, null, 'New York Jets', 'Green Bay Packers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w6-raiders-lions', 'W6', 6, null, null, 'Detroit Lions', 'Las Vegas Raiders', null, null, 'scheduled', false, false, 'NFC North', ''),
('w6-commanders-patriots', 'W6', 6, null, null, 'New England Patriots', 'Washington Commanders', null, null, 'scheduled', false, false, 'NFC East', ''),
('w6-saints-seahawks', 'W6', 6, null, null, 'Seattle Seahawks', 'New Orleans Saints', null, null, 'scheduled', false, false, 'NFC West', ''),
('w6-panthers-steelers', 'W6', 6, null, null, 'Pittsburgh Steelers', 'Carolina Panthers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w6-cardinals-vikings', 'W6', 6, null, null, 'Minnesota Vikings', 'Arizona Cardinals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w7-cowboys-bengals', 'W7', 7, null, null, 'Cincinnati Bengals', 'Dallas Cowboys', null, null, 'scheduled', false, false, 'NFC East', ''),
('w7-panthers-bills', 'W7', 7, null, null, 'Buffalo Bills', 'Carolina Panthers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w7-colts-cardinals', 'W7', 7, null, null, 'Arizona Cardinals', 'Indianapolis Colts', null, null, 'scheduled', false, false, 'NFC West', ''),
('w7-browns-commanders', 'W7', 7, null, null, 'Washington Commanders', 'Cleveland Browns', null, null, 'scheduled', false, false, 'NFC East', ''),
('w7-eagles-dolphins', 'W7', 7, null, null, 'Miami Dolphins', 'Philadelphia Eagles', null, null, 'scheduled', false, false, 'NFC East', ''),
('w7-giants-falcons', 'W7', 7, null, null, 'Atlanta Falcons', 'New York Giants', null, null, 'scheduled', false, false, 'NFC South', ''),
('w7-packers-jaguars', 'W7', 7, null, null, 'Jacksonville Jaguars', 'Green Bay Packers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w7-steelers-lions', 'W7', 7, null, null, 'Detroit Lions', 'Pittsburgh Steelers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w7-bears-patriots', 'W7', 7, null, null, 'New England Patriots', 'Chicago Bears', null, null, 'scheduled', false, false, 'NFC North', ''),
('w7-seahawks-ravens', 'W7', 7, null, null, 'Baltimore Ravens', 'Seattle Seahawks', null, null, 'scheduled', false, false, 'NFC West', ''),
('w7-49ers-saints', 'W7', 7, null, null, 'New Orleans Saints', 'San Francisco 49ers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w7-rams-texans', 'W7', 7, null, null, 'Houston Texans', 'Los Angeles Rams', null, null, 'scheduled', false, false, 'NFC West', ''),
('w7-buccaneers-titans', 'W7', 7, null, null, 'Tennessee Titans', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w7-jets-vikings', 'W7', 7, null, null, 'Minnesota Vikings', 'New York Jets', null, null, 'scheduled', false, false, 'NFC North', ''),
('w8-packers-bills', 'W8', 8, null, null, 'Buffalo Bills', 'Green Bay Packers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w8-buccaneers-browns', 'W8', 8, null, null, 'Cleveland Browns', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w8-panthers-chargers', 'W8', 8, null, null, 'Los Angeles Chargers', 'Carolina Panthers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w8-commanders-chiefs', 'W8', 8, null, null, 'Kansas City Chiefs', 'Washington Commanders', null, null, 'scheduled', false, false, 'NFC East', ''),
('w8-falcons-colts', 'W8', 8, null, null, 'Indianapolis Colts', 'Atlanta Falcons', null, null, 'scheduled', false, false, 'NFC South', ''),
('w8-vikings-dolphins', 'W8', 8, null, null, 'Miami Dolphins', 'Minnesota Vikings', null, null, 'scheduled', false, false, 'NFC North', ''),
('w8-patriots-eagles', 'W8', 8, null, null, 'Philadelphia Eagles', 'New England Patriots', null, null, 'scheduled', false, false, 'NFC East', ''),
('w8-rams-jaguars', 'W8', 8, null, null, 'Jacksonville Jaguars', 'Los Angeles Rams', null, null, 'scheduled', false, false, 'NFC West', ''),
('w8-broncos-jets', 'W8', 8, null, null, 'New York Jets', 'Denver Broncos', null, null, 'scheduled', false, false, 'AFC West', ''),
('w8-49ers-lions', 'W8', 8, null, null, 'Detroit Lions', 'San Francisco 49ers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w8-bengals-raiders', 'W8', 8, null, null, 'Las Vegas Raiders', 'Cincinnati Bengals', null, null, 'scheduled', false, false, 'AFC West', ''),
('w8-cardinals-ravens', 'W8', 8, null, null, 'Baltimore Ravens', 'Arizona Cardinals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w8-titans-saints', 'W8', 8, null, null, 'New Orleans Saints', 'Tennessee Titans', null, null, 'scheduled', false, false, 'NFC South', ''),
('w8-texans-seahawks', 'W8', 8, null, null, 'Seattle Seahawks', 'Houston Texans', null, null, 'scheduled', false, false, 'NFC West', ''),
('w8-bears-steelers', 'W8', 8, null, null, 'Pittsburgh Steelers', 'Chicago Bears', null, null, 'scheduled', false, false, 'NFC North', ''),
('w9-dolphins-49ers', 'W9', 9, null, null, 'San Francisco 49ers', 'Miami Dolphins', null, null, 'scheduled', false, false, 'NFC West', ''),
('w9-colts-bears', 'W9', 9, null, null, 'Chicago Bears', 'Indianapolis Colts', null, null, 'scheduled', false, false, 'NFC North', ''),
('w9-cardinals-bengals', 'W9', 9, null, null, 'Cincinnati Bengals', 'Arizona Cardinals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w9-cowboys-browns', 'W9', 9, null, null, 'Cleveland Browns', 'Dallas Cowboys', null, null, 'scheduled', false, false, 'NFC East', ''),
('w9-rams-buccaneers', 'W9', 9, null, null, 'Tampa Bay Buccaneers', 'Los Angeles Rams', null, null, 'scheduled', false, false, 'NFC West', ''),
('w9-falcons-chargers', 'W9', 9, null, null, 'Los Angeles Chargers', 'Atlanta Falcons', null, null, 'scheduled', false, false, 'NFC South', ''),
('w9-titans-giants', 'W9', 9, null, null, 'New York Giants', 'Tennessee Titans', null, null, 'scheduled', false, false, 'NFC East', ''),
('w9-bills-jaguars', 'W9', 9, null, null, 'Jacksonville Jaguars', 'Buffalo Bills', null, null, 'scheduled', false, false, 'AFC South', ''),
('w9-raiders-jets', 'W9', 9, null, null, 'New York Jets', 'Las Vegas Raiders', null, null, 'scheduled', false, false, 'AFC West', ''),
('w9-texans-lions', 'W9', 9, null, null, 'Detroit Lions', 'Houston Texans', null, null, 'scheduled', false, false, 'NFC North', ''),
('w9-ravens-packers', 'W9', 9, null, null, 'Green Bay Packers', 'Baltimore Ravens', null, null, 'scheduled', false, false, 'NFC North', ''),
('w9-broncos-panthers', 'W9', 9, null, null, 'Carolina Panthers', 'Denver Broncos', null, null, 'scheduled', false, false, 'NFC South', ''),
('w9-saints-patriots', 'W9', 9, null, null, 'New England Patriots', 'New Orleans Saints', null, null, 'scheduled', false, false, 'NFC South', ''),
('w9-chiefs-seahawks', 'W9', 9, null, null, 'Seattle Seahawks', 'Kansas City Chiefs', null, null, 'scheduled', false, false, 'NFC West', ''),
('w9-vikings-steelers', 'W9', 9, null, null, 'Pittsburgh Steelers', 'Minnesota Vikings', null, null, 'scheduled', false, false, 'NFC North', ''),
('w10-colts-49ers', 'W10', 10, null, null, 'San Francisco 49ers', 'Indianapolis Colts', null, null, 'scheduled', false, false, 'NFC West', ''),
('w10-chargers-bills', 'W10', 10, null, null, 'Buffalo Bills', 'Los Angeles Chargers', null, null, 'scheduled', false, false, 'AFC West', ''),
('w10-saints-broncos', 'W10', 10, null, null, 'Denver Broncos', 'New Orleans Saints', null, null, 'scheduled', false, false, 'NFC South', ''),
('w10-seahawks-buccaneers', 'W10', 10, null, null, 'Tampa Bay Buccaneers', 'Seattle Seahawks', null, null, 'scheduled', false, false, 'NFC West', ''),
('w10-dolphins-cardinals', 'W10', 10, null, null, 'Arizona Cardinals', 'Miami Dolphins', null, null, 'scheduled', false, false, 'NFC West', ''),
('w10-eagles-chiefs', 'W10', 10, null, null, 'Kansas City Chiefs', 'Philadelphia Eagles', null, null, 'scheduled', false, false, 'NFC East', ''),
('w10-jaguars-commanders', 'W10', 10, null, null, 'Washington Commanders', 'Jacksonville Jaguars', null, null, 'scheduled', false, false, 'NFC East', ''),
('w10-jets-cowboys', 'W10', 10, null, null, 'Dallas Cowboys', 'New York Jets', null, null, 'scheduled', false, false, 'NFC East', ''),
('w10-steelers-falcons', 'W10', 10, null, null, 'Atlanta Falcons', 'Pittsburgh Steelers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w10-ravens-giants', 'W10', 10, null, null, 'New York Giants', 'Baltimore Ravens', null, null, 'scheduled', false, false, 'NFC East', ''),
('w10-texans-panthers', 'W10', 10, null, null, 'Carolina Panthers', 'Houston Texans', null, null, 'scheduled', false, false, 'NFC South', ''),
('w10-browns-raiders', 'W10', 10, null, null, 'Las Vegas Raiders', 'Cleveland Browns', null, null, 'scheduled', false, false, 'AFC West', ''),
('w10-bengals-rams', 'W10', 10, null, null, 'Los Angeles Rams', 'Cincinnati Bengals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w10-bears-titans', 'W10', 10, null, null, 'Tennessee Titans', 'Chicago Bears', null, null, 'scheduled', false, false, 'NFC North', ''),
('w10-patriots-vikings', 'W10', 10, null, null, 'Minnesota Vikings', 'New England Patriots', null, null, 'scheduled', false, false, 'NFC North', ''),
('w11-cowboys-bills', 'W11', 11, null, null, 'Buffalo Bills', 'Dallas Cowboys', null, null, 'scheduled', false, false, 'NFC East', ''),
('w11-falcons-broncos', 'W11', 11, null, null, 'Denver Broncos', 'Atlanta Falcons', null, null, 'scheduled', false, false, 'NFC South', ''),
('w11-jets-buccaneers', 'W11', 11, null, null, 'Tampa Bay Buccaneers', 'New York Jets', null, null, 'scheduled', false, false, 'NFC South', ''),
('w11-chiefs-cardinals', 'W11', 11, null, null, 'Arizona Cardinals', 'Kansas City Chiefs', null, null, 'scheduled', false, false, 'NFC West', ''),
('w11-jaguars-chargers', 'W11', 11, null, null, 'Los Angeles Chargers', 'Jacksonville Jaguars', null, null, 'scheduled', false, false, 'AFC West', ''),
('w11-eagles-colts', 'W11', 11, null, null, 'Indianapolis Colts', 'Philadelphia Eagles', null, null, 'scheduled', false, false, 'NFC East', ''),
('w11-lions-commanders', 'W11', 11, null, null, 'Washington Commanders', 'Detroit Lions', null, null, 'scheduled', false, false, 'NFC North', ''),
('w11-rams-dolphins', 'W11', 11, null, null, 'Miami Dolphins', 'Los Angeles Rams', null, null, 'scheduled', false, false, 'NFC West', ''),
('w11-saints-giants', 'W11', 11, null, null, 'New York Giants', 'New Orleans Saints', null, null, 'scheduled', false, false, 'NFC South', ''),
('w11-bengals-packers', 'W11', 11, null, null, 'Green Bay Packers', 'Cincinnati Bengals', null, null, 'scheduled', false, false, 'NFC North', ''),
('w11-raiders-panthers', 'W11', 11, null, null, 'Carolina Panthers', 'Las Vegas Raiders', null, null, 'scheduled', false, false, 'NFC South', ''),
('w11-seahawks-patriots', 'W11', 11, null, null, 'New England Patriots', 'Seattle Seahawks', null, null, 'scheduled', false, false, 'NFC West', ''),
('w11-texans-ravens', 'W11', 11, null, null, 'Baltimore Ravens', 'Houston Texans', null, null, 'scheduled', false, false, 'AFC South', ''),
('w11-49ers-steelers', 'W11', 11, null, null, 'Pittsburgh Steelers', 'San Francisco 49ers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w11-browns-titans', 'W11', 11, null, null, 'Tennessee Titans', 'Cleveland Browns', null, null, 'scheduled', false, false, 'AFC South', ''),
('w12-bengals-49ers', 'W12', 12, null, null, 'San Francisco 49ers', 'Cincinnati Bengals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w12-bills-bears', 'W12', 12, null, null, 'Chicago Bears', 'Buffalo Bills', null, null, 'scheduled', false, false, 'NFC North', ''),
('w12-lions-broncos', 'W12', 12, null, null, 'Denver Broncos', 'Detroit Lions', null, null, 'scheduled', false, false, 'NFC North', ''),
('w12-browns-chiefs', 'W12', 12, null, null, 'Kansas City Chiefs', 'Cleveland Browns', null, null, 'scheduled', false, false, 'AFC West', ''),
('w12-cowboys-colts', 'W12', 12, null, null, 'Indianapolis Colts', 'Dallas Cowboys', null, null, 'scheduled', false, false, 'NFC East', ''),
('w12-seahawks-dolphins', 'W12', 12, null, null, 'Miami Dolphins', 'Seattle Seahawks', null, null, 'scheduled', false, false, 'NFC West', ''),
('w12-jaguars-eagles', 'W12', 12, null, null, 'Philadelphia Eagles', 'Jacksonville Jaguars', null, null, 'scheduled', false, false, 'NFC East', ''),
('w12-vikings-giants', 'W12', 12, null, null, 'New York Giants', 'Minnesota Vikings', null, null, 'scheduled', false, false, 'NFC North', ''),
('w12-chargers-jets', 'W12', 12, null, null, 'New York Jets', 'Los Angeles Chargers', null, null, 'scheduled', false, false, 'AFC West', ''),
('w12-texans-packers', 'W12', 12, null, null, 'Green Bay Packers', 'Houston Texans', null, null, 'scheduled', false, false, 'NFC North', ''),
('w12-patriots-panthers', 'W12', 12, null, null, 'Carolina Panthers', 'New England Patriots', null, null, 'scheduled', false, false, 'NFC South', ''),
('w12-rams-raiders', 'W12', 12, null, null, 'Las Vegas Raiders', 'Los Angeles Rams', null, null, 'scheduled', false, false, 'NFC West', ''),
('w12-saints-ravens', 'W12', 12, null, null, 'Baltimore Ravens', 'New Orleans Saints', null, null, 'scheduled', false, false, 'NFC South', ''),
('w12-cardinals-steelers', 'W12', 12, null, null, 'Pittsburgh Steelers', 'Arizona Cardinals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w12-commanders-titans', 'W12', 12, null, null, 'Tennessee Titans', 'Washington Commanders', null, null, 'scheduled', false, false, 'NFC East', ''),
('w13-chiefs-49ers', 'W13', 13, null, null, 'San Francisco 49ers', 'Kansas City Chiefs', null, null, 'scheduled', false, false, 'NFC West', ''),
('w13-chargers-bengals', 'W13', 13, null, null, 'Cincinnati Bengals', 'Los Angeles Chargers', null, null, 'scheduled', false, false, 'AFC West', ''),
('w13-lions-bills', 'W13', 13, null, null, 'Buffalo Bills', 'Detroit Lions', null, null, 'scheduled', false, false, 'NFC North', ''),
('w13-browns-broncos', 'W13', 13, null, null, 'Denver Broncos', 'Cleveland Browns', null, null, 'scheduled', false, false, 'AFC West', ''),
('w13-cardinals-buccaneers', 'W13', 13, null, null, 'Tampa Bay Buccaneers', 'Arizona Cardinals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w13-giants-colts', 'W13', 13, null, null, 'Indianapolis Colts', 'New York Giants', null, null, 'scheduled', false, false, 'NFC East', ''),
('w13-dolphins-commanders', 'W13', 13, null, null, 'Washington Commanders', 'Miami Dolphins', null, null, 'scheduled', false, false, 'NFC East', ''),
('w13-titans-cowboys', 'W13', 13, null, null, 'Dallas Cowboys', 'Tennessee Titans', null, null, 'scheduled', false, false, 'NFC East', ''),
('w13-jets-eagles', 'W13', 13, null, null, 'Philadelphia Eagles', 'New York Jets', null, null, 'scheduled', false, false, 'NFC East', ''),
('w13-jaguars-falcons', 'W13', 13, null, null, 'Atlanta Falcons', 'Jacksonville Jaguars', null, null, 'scheduled', false, false, 'NFC South', ''),
('w13-patriots-packers', 'W13', 13, null, null, 'Green Bay Packers', 'New England Patriots', null, null, 'scheduled', false, false, 'NFC North', ''),
('w13-ravens-raiders', 'W13', 13, null, null, 'Las Vegas Raiders', 'Baltimore Ravens', null, null, 'scheduled', false, false, 'AFC West', ''),
('w13-steelers-rams', 'W13', 13, null, null, 'Los Angeles Rams', 'Pittsburgh Steelers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w13-vikings-seahawks', 'W13', 13, null, null, 'Seattle Seahawks', 'Minnesota Vikings', null, null, 'scheduled', false, false, 'NFC West', ''),
('w13-bears-texans', 'W13', 13, null, null, 'Houston Texans', 'Chicago Bears', null, null, 'scheduled', false, false, 'NFC North', ''),
('w14-dolphins-bears', 'W14', 14, null, null, 'Chicago Bears', 'Miami Dolphins', null, null, 'scheduled', false, false, 'NFC North', ''),
('w14-broncos-bengals', 'W14', 14, null, null, 'Cincinnati Bengals', 'Denver Broncos', null, null, 'scheduled', false, false, 'AFC West', ''),
('w14-eagles-browns', 'W14', 14, null, null, 'Cleveland Browns', 'Philadelphia Eagles', null, null, 'scheduled', false, false, 'NFC East', ''),
('w14-titans-chargers', 'W14', 14, null, null, 'Los Angeles Chargers', 'Tennessee Titans', null, null, 'scheduled', false, false, 'AFC West', ''),
('w14-giants-chiefs', 'W14', 14, null, null, 'Kansas City Chiefs', 'New York Giants', null, null, 'scheduled', false, false, 'NFC East', ''),
('w14-commanders-colts', 'W14', 14, null, null, 'Indianapolis Colts', 'Washington Commanders', null, null, 'scheduled', false, false, 'NFC East', ''),
('w14-lions-falcons', 'W14', 14, null, null, 'Atlanta Falcons', 'Detroit Lions', null, null, 'scheduled', false, false, 'NFC South', ''),
('w14-raiders-jaguars', 'W14', 14, null, null, 'Jacksonville Jaguars', 'Las Vegas Raiders', null, null, 'scheduled', false, false, 'AFC West', ''),
('w14-panthers-jets', 'W14', 14, null, null, 'New York Jets', 'Carolina Panthers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w14-steelers-packers', 'W14', 14, null, null, 'Green Bay Packers', 'Pittsburgh Steelers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w14-cowboys-patriots', 'W14', 14, null, null, 'New England Patriots', 'Dallas Cowboys', null, null, 'scheduled', false, false, 'NFC East', ''),
('w14-saints-rams', 'W14', 14, null, null, 'Los Angeles Rams', 'New Orleans Saints', null, null, 'scheduled', false, false, 'NFC West', ''),
('w14-buccaneers-ravens', 'W14', 14, null, null, 'Baltimore Ravens', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w14-cardinals-texans', 'W14', 14, null, null, 'Houston Texans', 'Arizona Cardinals', null, null, 'scheduled', false, false, 'NFC West', ''),
('w14-bills-vikings', 'W14', 14, null, null, 'Minnesota Vikings', 'Buffalo Bills', null, null, 'scheduled', false, false, 'NFC North', ''),
('w15-buccaneers-49ers', 'W15', 15, null, null, 'San Francisco 49ers', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w15-giants-bengals', 'W15', 15, null, null, 'Cincinnati Bengals', 'New York Giants', null, null, 'scheduled', false, false, 'NFC East', ''),
('w15-jaguars-broncos', 'W15', 15, null, null, 'Denver Broncos', 'Jacksonville Jaguars', null, null, 'scheduled', false, false, 'AFC West', ''),
('w15-chargers-browns', 'W15', 15, null, null, 'Cleveland Browns', 'Los Angeles Chargers', null, null, 'scheduled', false, false, 'AFC West', ''),
('w15-bears-chiefs', 'W15', 15, null, null, 'Kansas City Chiefs', 'Chicago Bears', null, null, 'scheduled', false, false, 'NFC North', ''),
('w15-packers-colts', 'W15', 15, null, null, 'Indianapolis Colts', 'Green Bay Packers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w15-jets-commanders', 'W15', 15, null, null, 'Washington Commanders', 'New York Jets', null, null, 'scheduled', false, false, 'NFC East', ''),
('w15-ravens-cowboys', 'W15', 15, null, null, 'Dallas Cowboys', 'Baltimore Ravens', null, null, 'scheduled', false, false, 'NFC East', ''),
('w15-panthers-dolphins', 'W15', 15, null, null, 'Miami Dolphins', 'Carolina Panthers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w15-titans-eagles', 'W15', 15, null, null, 'Philadelphia Eagles', 'Tennessee Titans', null, null, 'scheduled', false, false, 'NFC East', ''),
('w15-raiders-falcons', 'W15', 15, null, null, 'Atlanta Falcons', 'Las Vegas Raiders', null, null, 'scheduled', false, false, 'NFC South', ''),
('w15-patriots-lions', 'W15', 15, null, null, 'Detroit Lions', 'New England Patriots', null, null, 'scheduled', false, false, 'NFC North', ''),
('w15-bills-saints', 'W15', 15, null, null, 'New Orleans Saints', 'Buffalo Bills', null, null, 'scheduled', false, false, 'NFC South', ''),
('w15-steelers-seahawks', 'W15', 15, null, null, 'Seattle Seahawks', 'Pittsburgh Steelers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w15-vikings-texans', 'W15', 15, null, null, 'Houston Texans', 'Minnesota Vikings', null, null, 'scheduled', false, false, 'NFC North', ''),
('w16-vikings-bears', 'W16', 16, null, null, 'Chicago Bears', 'Minnesota Vikings', null, null, 'scheduled', false, false, 'NFC North', ''),
('w16-ravens-bengals', 'W16', 16, null, null, 'Cincinnati Bengals', 'Baltimore Ravens', null, null, 'scheduled', false, false, 'AFC North', ''),
('w16-rams-cardinals', 'W16', 16, null, null, 'Arizona Cardinals', 'Los Angeles Rams', null, null, 'scheduled', false, false, 'NFC West', ''),
('w16-raiders-chargers', 'W16', 16, null, null, 'Los Angeles Chargers', 'Las Vegas Raiders', null, null, 'scheduled', false, false, 'AFC West', ''),
('w16-broncos-chiefs', 'W16', 16, null, null, 'Kansas City Chiefs', 'Denver Broncos', null, null, 'scheduled', false, false, 'AFC West', ''),
('w16-texans-colts', 'W16', 16, null, null, 'Indianapolis Colts', 'Houston Texans', null, null, 'scheduled', false, false, 'AFC South', ''),
('w16-eagles-commanders', 'W16', 16, null, null, 'Washington Commanders', 'Philadelphia Eagles', null, null, 'scheduled', false, false, 'NFC East', ''),
('w16-bills-dolphins', 'W16', 16, null, null, 'Miami Dolphins', 'Buffalo Bills', null, null, 'scheduled', false, false, 'AFC East', ''),
('w16-buccaneers-falcons', 'W16', 16, null, null, 'Atlanta Falcons', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w16-cowboys-giants', 'W16', 16, null, null, 'New York Giants', 'Dallas Cowboys', null, null, 'scheduled', false, false, 'NFC East', ''),
('w16-patriots-jets', 'W16', 16, null, null, 'New York Jets', 'New England Patriots', null, null, 'scheduled', false, false, 'AFC East', ''),
('w16-packers-lions', 'W16', 16, null, null, 'Detroit Lions', 'Green Bay Packers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w16-saints-panthers', 'W16', 16, null, null, 'Carolina Panthers', 'New Orleans Saints', null, null, 'scheduled', false, false, 'NFC South', ''),
('w16-49ers-seahawks', 'W16', 16, null, null, 'Seattle Seahawks', 'San Francisco 49ers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w16-browns-steelers', 'W16', 16, null, null, 'Pittsburgh Steelers', 'Cleveland Browns', null, null, 'scheduled', false, false, 'AFC North', ''),
('w16-jaguars-titans', 'W16', 16, null, null, 'Tennessee Titans', 'Jacksonville Jaguars', null, null, 'scheduled', false, false, 'AFC South', ''),
('w17-lions-bears', 'W17', 17, null, null, 'Chicago Bears', 'Detroit Lions', null, null, 'scheduled', false, false, 'NFC North', ''),
('w17-ravens-browns', 'W17', 17, null, null, 'Cleveland Browns', 'Baltimore Ravens', null, null, 'scheduled', false, false, 'AFC North', ''),
('w17-seahawks-cardinals', 'W17', 17, null, null, 'Arizona Cardinals', 'Seattle Seahawks', null, null, 'scheduled', false, false, 'NFC West', ''),
('w17-chiefs-chargers', 'W17', 17, null, null, 'Los Angeles Chargers', 'Kansas City Chiefs', null, null, 'scheduled', false, false, 'AFC West', ''),
('w17-giants-commanders', 'W17', 17, null, null, 'Washington Commanders', 'New York Giants', null, null, 'scheduled', false, false, 'NFC East', ''),
('w17-cowboys-eagles', 'W17', 17, null, null, 'Philadelphia Eagles', 'Dallas Cowboys', null, null, 'scheduled', false, false, 'NFC East', ''),
('w17-texans-jaguars', 'W17', 17, null, null, 'Jacksonville Jaguars', 'Houston Texans', null, null, 'scheduled', false, false, 'AFC South', ''),
('w17-dolphins-jets', 'W17', 17, null, null, 'New York Jets', 'Miami Dolphins', null, null, 'scheduled', false, false, 'AFC East', ''),
('w17-falcons-panthers', 'W17', 17, null, null, 'Carolina Panthers', 'Atlanta Falcons', null, null, 'scheduled', false, false, 'NFC South', ''),
('w17-bills-patriots', 'W17', 17, null, null, 'New England Patriots', 'Buffalo Bills', null, null, 'scheduled', false, false, 'AFC East', ''),
('w17-broncos-raiders', 'W17', 17, null, null, 'Las Vegas Raiders', 'Denver Broncos', null, null, 'scheduled', false, false, 'AFC West', ''),
('w17-49ers-rams', 'W17', 17, null, null, 'Los Angeles Rams', 'San Francisco 49ers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w17-buccaneers-saints', 'W17', 17, null, null, 'New Orleans Saints', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w17-bengals-steelers', 'W17', 17, null, null, 'Pittsburgh Steelers', 'Cincinnati Bengals', null, null, 'scheduled', false, false, 'AFC North', ''),
('w17-colts-titans', 'W17', 17, null, null, 'Tennessee Titans', 'Indianapolis Colts', null, null, 'scheduled', false, false, 'AFC South', ''),
('w17-packers-vikings', 'W17', 17, null, null, 'Minnesota Vikings', 'Green Bay Packers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w18-packers-bears', 'W18', 18, null, null, 'Chicago Bears', 'Green Bay Packers', null, null, 'scheduled', false, false, 'NFC North', ''),
('w18-bengals-browns', 'W18', 18, null, null, 'Cleveland Browns', 'Cincinnati Bengals', null, null, 'scheduled', false, false, 'AFC North', ''),
('w18-49ers-cardinals', 'W18', 18, null, null, 'Arizona Cardinals', 'San Francisco 49ers', null, null, 'scheduled', false, false, 'NFC West', ''),
('w18-broncos-chargers', 'W18', 18, null, null, 'Los Angeles Chargers', 'Denver Broncos', null, null, 'scheduled', false, false, 'AFC West', ''),
('w18-cowboys-commanders', 'W18', 18, null, null, 'Washington Commanders', 'Dallas Cowboys', null, null, 'scheduled', false, false, 'NFC East', ''),
('w18-giants-eagles', 'W18', 18, null, null, 'Philadelphia Eagles', 'New York Giants', null, null, 'scheduled', false, false, 'NFC East', ''),
('w18-colts-jaguars', 'W18', 18, null, null, 'Jacksonville Jaguars', 'Indianapolis Colts', null, null, 'scheduled', false, false, 'AFC South', ''),
('w18-bills-jets', 'W18', 18, null, null, 'New York Jets', 'Buffalo Bills', null, null, 'scheduled', false, false, 'AFC East', ''),
('w18-buccaneers-panthers', 'W18', 18, null, null, 'Carolina Panthers', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, false, 'NFC South', ''),
('w18-dolphins-patriots', 'W18', 18, null, null, 'New England Patriots', 'Miami Dolphins', null, null, 'scheduled', false, false, 'AFC East', ''),
('w18-chiefs-raiders', 'W18', 18, null, null, 'Las Vegas Raiders', 'Kansas City Chiefs', null, null, 'scheduled', false, false, 'AFC West', ''),
('w18-seahawks-rams', 'W18', 18, null, null, 'Los Angeles Rams', 'Seattle Seahawks', null, null, 'scheduled', false, false, 'NFC West', ''),
('w18-falcons-saints', 'W18', 18, null, null, 'New Orleans Saints', 'Atlanta Falcons', null, null, 'scheduled', false, false, 'NFC South', ''),
('w18-ravens-steelers', 'W18', 18, null, null, 'Pittsburgh Steelers', 'Baltimore Ravens', null, null, 'scheduled', false, false, 'AFC North', ''),
('w18-texans-titans', 'W18', 18, null, null, 'Tennessee Titans', 'Houston Texans', null, null, 'scheduled', false, false, 'AFC South', ''),
('w18-lions-vikings', 'W18', 18, null, null, 'Minnesota Vikings', 'Detroit Lions', null, null, 'scheduled', false, false, 'NFC North', '')
on conflict (id) do update set
  week = excluded.week,
  week_number = excluded.week_number,
  game_date = excluded.game_date,
  kickoff_time = excluded.kickoff_time,
  home_team_name = excluded.home_team_name,
  away_team_name = excluded.away_team_name,
  home_score = excluded.home_score,
  away_score = excluded.away_score,
  status = excluded.status,
  is_live = excluded.is_live,
  spotlight = excluded.spotlight,
  source_sheet = excluded.source_sheet,
  note = excluded.note;

insert into public.site_settings (key, value) values
('season_banner', '{"title":"Season 4 Week 1","subtitle":"NTFL Network"}'::jsonb),
('home_banner', '{"headline":"Where the NTFL collides","cta":"Commissioner Control Center"}'::jsonb),
('rules', '{"title":"League Rules","body":"Add your NTFL rules here."}'::jsonb)
on conflict (key) do update set value = excluded.value;

commit;
